const SIMULATION_DURATION = 150
const NUM_OF_PRODUCERS = 10
const NUM_OF_CONSUMERS = 10
 
const MAX_STARTING_SUPPLY = 20
const SUPPLY_INCREMENT = 80
 
const COST = 5
const MAX_ACCEPTABLE_PRICE = COST * 10
const MAX_STARTING_PROFIT = 5
const PRICE_INCREMENT = 1.1
const PRICE_DECREMENT = 0.9

